mongodb_repository_information_file_destination: /etc/yum.repos.d

database_name: kata-db
database_user: kata
database_password: "{{ lookup('amazon.aws.ssm_parameter', '/' + ssm_prefix + '/database/password', decrypt=true, region='eu-west-1') }}"
database_backup_directory: /var/backups/mongodb/