- name: Sleep for 10 seconds
  become: true
  command: sleep 10

- name: Creating MongoDB database
  become: true
  shell: mongosh --eval "db.getSiblingDB('{{ database_name }}').createCollection('empty')"

- name: Creating MongoDB user
  shell: |
    mongosh --eval "
    db.getSiblingDB('{{ database_name }}').createUser({
      user: '{{ database_user }}',
      pwd: '{{ database_password }}',
      roles: ['readWrite']
    })
    "
- name: Schedule mongodump with cron
  cron:
    name: Perform MongoDB backup
    minute: 0
    hour: 0
    weekday: 0
    job: mongodump --db kata-db --out /var/backups/mongobackups/`date +"%m-%d-%y"` >/dev/null 2>&1