- name: Sleep for 10 seconds
  become: true
  command: sleep 10

- name: Creating MongoDB database
  shell: mongosh --eval "db.getSiblingDB('{{ database_name }}')"
  become: true

- name: Creating MongoDB user
  shell: |
    mongosh --eval "
    db.getSiblingDB('{{ database_name }}').createUser({
      user: '{{ database_user }}',
      pwd: '{{ database_password }}',
      roles: ["readWrite"]
    })
    "


  # mongodb_user:
  #   database: "{{ database_name }}"
  #   name: "{{ database_user }}"
  #   password: "{{ database_password }}"
  #   roles:
  #     - readWrite