- name: Sleep for 10 seconds
  become: true
  command: sleep 10

- name: Creating MongoDB database
  become: true
  shell: mongosh --eval "db.getSiblingDB('{{ database_name }}').createCollection('empty')"

- name: Creating MongoDB user
  become: true
  shell: |
    mongosh --eval "
    db.getSiblingDB('{{ database_name }}').createUser({
      user: '{{ database_user }}',
      pwd: '{{ database_password }}',
      roles: ['readWrite']
    })
    "
- name: Create MongoDB Backup Directory
  become: true
  file:
    path: "{{ database_backup_directory }}"
    state: directory
    mode: '0755'

- name: Database Backup Every 7 Days
  become: true
  cron:
    name: MOngoDB Backup
    minute: 0
    hour: 0
    weekday: 0
    job: mongodump --db kata-db --out {{ database_backup_directory }}`date +"%m-%d-%y"` >/dev/null 2>&1