- name: Creating MongoDB database
  shell: mongo --eval 'db.getSiblingDB("{{ database_name }}")'

- name: Creating MongoDB user
  mongodb_user:
    database: "{{ database_name }}"
    name: "{{ database_user }}"
    password: "{{ database_password }}"
    roles:
      - readWrite