- name: Copy Application Service
  become: true
  template:
    src: cloud-phoenix-kata.service.j2
    dest: "{{ application_service_destination }}"

- name: Start The Application Service 
  become: true
  service: 
    name: cloud-phoenix-cata
    state: started
    enabled: yes